### ISSUE TITLE
Version discrepancy

### ISSUE THREAD

**Issue by needalight** [banteg/multicall.py#14]
Recently Multicall2 support has been added with version upgrade to 0.1.3: https://github.com/banteg/multicall.py/pull/8
But then 0.1.3 tag was added to an older version of the files.
![image](https://user-images.githubusercontent.com/79828237/147866856-5bf8fe28-02f4-44c5-8657-47b0d33d19a7.png)
And now the last version (0.1.3) doesn't come with Multicall2 suport

**Comment by BobTheBuidler** [comment]
closing as we are now many versions beyond this issue
