### ISSUE TITLE
Is there a way to make this work with remote Infura nodes?

### ISSUE THREAD

**Issue by seanroades** [banteg/multicall.py#29]
I'm just confused about how the provider is detected here--I think the project is great btw!

**Comment by seanroades** [comment]
Or I guess, how do I pass my web3 instance to this?

**Comment by seanroades** [comment]
Could not discover provider while making request: method:eth_chainId
params:() <- this is the error I'm getting

**Comment by BobTheBuidler** [comment]
Closing this issue as help as been provided by @heki-ru . Thanks heki!
