### ISSUE TITLE
Consider switching to ThreadPoolExecutor

### ISSUE THREAD

**Issue by stas** [banteg/multicall.py#38]
![Captura de ecrã de 2022-06-07 13 52 11](https://user-images.githubusercontent.com/112147/172384085-076f5fb1-f3ee-45bc-afe8-301f3780c1e2.png)

We're running `multicall` in a background worker and we could see an abnormal usage of the memory. After reviewing the implementation and switching to `concurrent.futures.ThreadPoolExecutor`, the processes stopped leaking memory.

Relevant line of code:
https://github.com/banteg/multicall.py/blob/master/multicall/utils.py#L27

**Comment by BobTheBuidler** [comment]
This was fixed in #44 .

Encoding/decoding now takes place serially, but multiprocessing can still be enabled via a "MULTICALL_PROCESSES" env var.
