### ISSUE TITLE
Access block number from the result dictionary

### ISSUE THREAD

**Issue by prabhatverma286** [banteg/multicall.py#39]
Looks like multicall returns the blockNumber during aggregate (or tryBlockAndAggregate) calls. 

However, it is omitted from the results dictionary: https://github.com/banteg/multicall.py/blob/master/multicall/multicall.py#L86

In cases where per-block data needs to be accessed and stored, it would be beneficial to know the block number on which the multicall request was performed on, saving the user from doing a separate web3.eth.block_number request just after the multicall request. 

Maybe the block number can be returned as '_block_number' in the results dictionary.

**Comment by BobTheBuidler** [comment]
closing this issue as we merged a similar feature a while back ^
