### ISSUE TITLE
add multicall v3 support

### ISSUE THREAD

**Issue by 007vasy** [banteg/multicall.py#49]
https://github.com/mds1/multicall

there is a new multicall version (v3) which is deployed over 50+ networks with the same address:
https://github.com/mds1/multicall#multicall3-contract-addresses

**Comment by 007vasy** [comment]
@banteg , @BobTheBuidler I can do this over the weekend (assign it to me)

**Comment by 007vasy** [comment]
hey folks could not finish it over the weekend, some tests are failing/ not even run when I got the new version

**Comment by BobTheBuidler** [comment]
are the 2 problem tests multicall in threads and multicall in multiprocessing?

**Comment by BobTheBuidler** [comment]
Can you submit what you do have as a draft PR so I can take a look?

**Comment by 007vasy** [comment]
https://github.com/007vasy/multicall.py/tree/task/add-mc-v3-contracts

**Comment by banteg** [comment]
completed by #52
