### ISSUE TITLE
Unable to use Multicall with threads in docker.

### ISSUE THREAD

**Issue by cbsystango** [banteg/multicall.py#53]
Docker throws following error when multicall is executed in threads(parallel execution)

![mcall_error](https://user-images.githubusercontent.com/89982831/199011612-15c8e66f-e252-4752-aa39-9020adc6ddbd.png)

**Comment by cbsystango** [comment]
Problem is resolved here: https://github.com/cbsystango/multicall-thread-safe/

**Comment by stas** [comment]
Confirming the latest build is broken for us as well.

@cbsystango running web3 calls in sub-processes is memory-expensive, see #38

**Comment by stas** [comment]
Downgrading web3.py to v5.27 worked.

**Comment by BobTheBuidler** [comment]
web3.py v5.28 thru v5.31.2 have issues with the async provider. v5.27 will work as will ^v5.31.3
