### ISSUE TITLE
How to call a function from web3.eth.*

### ISSUE THREAD

**Issue by VinhTruong2001** [banteg/multicall.py#65]
Hello, I need to use **Multicall** with **web3.eth.getCode()** but I don't know how to do that, I wanna check a list of addresses to know which is contract address. Could you help me. Thank you.

**Comment by BobTheBuidler** [comment]
You won't be able to do this using multicall. Check out my lib dank_mids if you want to batch your getCode calls into one batched RPC call. 

https://github.com/BobTheBuidler/dank_mids
