### ISSUE TITLE
 Could not discover provider

### ISSUE THREAD

**Issue by arachmanto** [banteg/multicall.py#7]
I running your code and there was an error:

web3.exceptions.CannotHandleRequest: Could not discover provider while making request: method:eth_chainId
params:()

Thank you

**Comment by mmd-mostafaee** [comment]
I have same issue :(

**Comment by DefiDebauchery** [comment]
This library uses web3.js' [Automatic Provider](https://web3py.readthedocs.io/en/stable/providers.html#automatic-vs-manual-providers). You can set the environment variable `WEB3_PROVIDER_URI` ([source](https://web3py.readthedocs.io/en/stable/providers.html#provider-via-environment-variable)) with an IPC, RPC, or Websocket address to connect to your endpoint.

You can also do it at runtime by adding the key/value to the `os.environ` structure.
```py
os.environ["WEB3_PROVIDER_URI"] = '...'
```

**Comment by 007vasy** [comment]
added help to my PRs readme
